

# Data 

mxmh_csv = "https://drive.google.com/file/d/1TTVy3RyYhsEul9RVI2q4jNYWxQeWr555/view?usp=sharing"
newdf_csv = "https://drive.google.com/file/d/1Ll8eikFqX9OY_D5_N8CKRYzozTiWp7Sm/view?usp=sharing"
uppdateddf_csv = "https://drive.google.com/file/d/1LHdZ4r-akL1AQX9ISrqb74dHzi7Loo0v/view?usp=sharing"


# Images

MentalHealthImage = "https://drive.google.com/file/d/1R9N2MKZ79AG3m-EN1bijMM6g8Dc9jFP5/view?usp=sharing"
marvelteam = "https://drive.google.com/file/d/1Y9-ASN7I18ggotenrSMzilnINSD4VlVm/view?usp=sharing"


# Audio Files

GammaWave = "https://drive.google.com/file/d/1eV9zfExcT2LdZSYv7av4DvpoT_d_YiY9/view?usp=sharing"
BetaWave = "https://drive.google.com/file/d/1mkqZ9pW8BPNbcdzZI_jr78OgO60PIzu-/view?usp=sharing"
AlphaWave = "https://drive.google.com/file/d/12d-7P4SKD_YPV-3_-Ml8JDdjUDcg0GMJ/view?usp=sharing"
ThetaWave = "https://drive.google.com/file/d/1pITIeABvrEegU4Zyc3Hw9qQXuICR8HIJ/view?usp=sharing"
DeltaWave = "https://drive.google.com/file/d/1Ljmrk1NDLP5vPI8aLdZ7MQoeHMC-t_jL/view?usp=sharing"
